### ISSUE TITLE
Request : Port code to Ubuntu via dot net core or mono? 

### ISSUE THREAD

**Issue by stjordanis** [marian42/wavefunctioncollapse#10]
Amazing work. Porting it to Linux would be fascinating
Maybe some instructions are already enough for that

**Comment by marian42** [comment]
I just tried to open the project with the latest version of Unity on Ubuntu and it worked just fine. I could even create a build. I'll upload a Linux build to the itch.io page in the coming days.

**Comment by stjordanis** [comment]
Instructions on the readme file on how to build it would be very helpful, thank you

**Comment by marian42** [comment]
There is not a lot to it. You need to have Unity installed. Clone the project somewhere and open it in the Unity Editor. Open the "Game" scene. Then you press the Play button to play. If you want to make a build, click `File` -> `Build and Run`.

**Comment by stjordanis** [comment]
The whole build process runs smoothly on ubuntu 18 and unity, it compiles and runs, but no buildings are rendered. Just blue sky and white earth. Any ideas?

**Comment by marian42** [comment]
It could be that you need to have Blender installed. Does the Unity Edtior show a warning about that? Can you see anything in the Prototypes scene?

**Comment by stjordanis** [comment]
No didn't have blender installed. No warnings about it were shown, thanks. 
The prototype scene is also void except for some codes like 2f, something like that. 
Will try  blender asap

**Comment by stjordanis** [comment]
yes it worked after installing blender  and wiping out the previous repo and starting from scratch! thank you
