### ISSUE TITLE
Development on a Mac?

### ISSUE THREAD

**Issue by jak2030** [marian42/wavefunctioncollapse#12]
I'm having trouble getting tiles to generate in Unity on a Mac.

Slots do seem to generate when I choose the default "Initialize 6x6 area":
<img width="1143" alt="slots" src="https://user-images.githubusercontent.com/1641058/60119101-ac442800-974b-11e9-939d-76cfb87ef505.png">

But when I enter gameplay, all I see is the skybox: 
<img width="1148" alt="skybox" src="https://user-images.githubusercontent.com/1641058/60119107-ae0deb80-974b-11e9-96d5-016715f2f8fe.png">

I'm not getting any info in the console and I made sure to run Unity 2018.3.0f2 (I also have Blender 2.79).

If I'm doing something obviously wrong, would love to know what it is! Otherwise, happy to help with a PR if you have a general sense of what might need to be changed for this to run on a Mac?

**Comment by marian42** [comment]
I think this is an issue with the blender file not loading correctly. Maybe Unity can't find the installation of Blender. What happens if you drag the `blocks.blend` file from the Assets folder into the scene?

**Comment by jak2030** [comment]
It seems like this actions doesn't do anything? It appears I can read the Blender file, only because:

A) I can see the Blender insignia on the icon in the Assets viewer.
B) I tried running the project in 2019.3.0a6 and originally got the error:

```
Blender could not convert the .blend file to FBX file. You need to use Blender 2.45-2.49 or 2.58 and later versions for direct Blender import to work.
```
And was able to resolve at least that problem with the two top solutions offered [here](https://answers.unity.com/questions/1622769/blender-could-not-convert-the-blend-file-to-fbx-fi-1.html) to swap in `Unity-BlenderToFBX.py` from a 2018.* version, or run Blender 2.8.

Neither of those options made the city visible in game mode, though it seems that when initializing an NxN area after following either of these steps, I do see the outlines of modules from the blender file:

<img width="1144" alt="scene2019-swappy" src="https://user-images.githubusercontent.com/1641058/60162080-ca9b3980-97c6-11e9-9c27-d06a7a9bb31c.png">

Also, FWIW, the other two strategies for building a world in the ReadMe (via the AreaSelector and ModuleData) do not appear to generate anything in the scene view.

**Comment by marian42** [comment]
If you drag the .blend file into the scene, you should see all the blocks. As long as that doesn't work, you won't be able to see the meshes anywhere else.

I'm not sure about Blender 2.8, I tried it but on Windows, Unity couldn't open .blend files that were created with Blender 2.8. The .blend file in the project was made with Blender 2.79.

If you want to avoid using Unity's Blender integration, you can do the following, which will be quite tedious:
- Open the blocks.blend file in Blender
- Export it using another format (such as .fbx) and add it to the Assets folder
- In the Prototypes prefab, replace the meshes of all MeshFilters with the ones from your .fbx file
- Select the ModuleData file and click "Create module data"
- Save

As I said, this would be a lot of work and I hope you find a way to import the Blender file instead.

**Comment by jak2030** [comment]
So, in the interest of closing this ticket, I can report my progress:

If I follow along with [other people's woes](https://forum.unity.com/threads/upgrading-to-2019-1-0f2-troubles-blend-import-broken-workaround.662623/) for OSX/Unity 2019.* and use Blender 2.8, I'm able to get tiles to start generating (though I am seeing partial tile generation alla #8  -- will keep exploring this and report back in that ticket if I discover any new solutions/info!)

As for 2018.3.0f2 with Blender 2.79, even after opening in Blender 2.79 and saving, I still get:

```
Blender could not convert the .blend file to FBX file.
You need to use Blender 2.45-2.49 or 2.58 and later versions for direct Blender import to work.
```

But, again, to conclude, the initial problem I was facing was that for some users (Mac users?), the jump to Unity 2019.* carries with it an expectation of also using Blender 2.8.

Thank you so much for your attention to this ticket @marian42 !
