### ISSUE TITLE
Change size of module

### ISSUE THREAD

**Issue by ztffn** [marian42/wavefunctioncollapse#13]
Hi, I'm trying to use your system with 200x200 blocks. How do I change the size of the gizmos and the ofset the world places the modules with?

**Comment by marian42** [comment]
Hi,

you need to change `AbstractMap.BLOCK_SIZE`.

I only ever used a size of 2. I just fixed some places where it was hardcoded. I hope I didn't miss any! It seems to work with other sizes though.

**Comment by ztffn** [comment]
Changed that value in AbstractMap.cs - which sorted the gizmos, but seems the neighbor preview/ghosts are still 2f it seems. 

https://imgur.com/32gj2Kp

Any idea where that offset might be found?

**Comment by marian42** [comment]
Did you pull the commit that I made an hour ago? That one should have fixed it.

**Comment by ztffn** [comment]
Works like a charm! Thank you very much - for sharing this great project and the quick feedback 👍
