### ISSUE TITLE
Use package manager version of Post Processing

### ISSUE THREAD

**Issue by andybak** [marian42/wavefunctioncollapse#3]
Then you won't need to say the following in the README:

> To view the project in Unity, import it and download the Postprocessing stack from the Asset Store. Alternatively, you can remove the Post Processing Behaviour from the Main Camera.

It won't clog up the repo (just a reference will be stored in package.json) but Unity will install it automatically as needed.

**Comment by marian42** [comment]
Thank you, I didn't know that. I'll do as you suggested soon.

**Comment by andybak** [comment]
I'll send a PR if I get a chance.

**Comment by marian42** [comment]
Thank you for the PR!
